packages:
  - 'packages/*'
  - 'examples/**'
  - '!**/dist/**'
verifyDepsBeforeRun: false
allowBuilds:
  '@biomejs/biome': true
  '@gez/router-vue': true
  esbuild: true
  core-js: false
  swiper: false
  puppeteer: false
  protobufjs: false
  less: false
