name = "esmx"
compatibility_date = "2024-01-01"

[build]
command = "npm install -g pnpm@10 && pnpm install --frozen-lockfile --ignore-engines && node ./build.mjs"
cwd = "."

[build.environment_variables]
NODE_VERSION = "22.16.0"
CF_PAGES = "1"

[assets]
directory = "./dist" 