name = "esmx"
compatibility_date = "2024-01-01"

[build]
command = "corepack enable && corepack prepare pnpm@10.11.1 --activate && node ./build.mjs"
cwd = "."

[build.environment_variables]
NODE_VERSION = "22.16.0"

[pages]
build_output_dir = "dist" 